[package]
name = "tokenizer_rs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tiktoken-rs = "0.9.1"
zstd = "0.13"

napi = { version = "2", features = ["napi6", "serde-json"] }
napi-derive = "2"
once_cell = "1"

[build-dependencies]
napi-build = "2"
