[package]
name = "json_accel_rs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde_json = "1"

napi = { version = "2", features = ["napi6", "serde-json"] }
napi-derive = "2"

simd-json = "0.17"

[build-dependencies]
napi-build = "2"
